const words = [
    'jul',
    'gambi',
    'sinik',
    'booba',
    'dadju',
    'maes',
    'koba la d',
    'mister v',
    'hamza',
    'pnl',
    'm pokora',
    'corneille',
    'soprano',
    'jaco',
    'kaaris',
    'plk',
    'maitre gims',
    'vald',
    'vegedream',
    'ninho',
    'la fouine',
    'nekfeu',
    'orelsan',
    'kery james',
    'soprano',
    'niska',
    'lacrim',
    'sch',
    'lomepal',
    'gradur',
    'dosseh',
    'kalash criminel',
    'kalash',
    'benash',
    'mhd',
    'black m',
    'joeystarr',
    'diams',
    'alonzo',
    'sadek',
    'alpha wann',
    'lefa',
    'heuss l\'enfoire'
]

module.exports = words;